
package frames;

/*****************************************
* Class Name: ResultFrame
* Purpose: A JFrame that displays a specific the
* results of a finished game
*******************************************/

import monopoly.engine.Player;
import monopoly.engine.Game;
import java.util.ArrayList;

public class ResultFrame extends javax.swing.JFrame 
{

    //constructor takes completed game as a parameter
    public ResultFrame(Game a_currentGame) 
    {
        m_finishedGame = a_currentGame;
        initComponents();
        playerThreePanel.setVisible(false);
        playerFourPanel.setVisible(false);
        setResults();
    }
/******************************************************************************/
    //The following code was generated by the form editor
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finalResults = new javax.swing.JLabel();
        playerOnePanel = new javax.swing.JPanel();
        playerOneName = new javax.swing.JLabel();
        playerOnePlace = new javax.swing.JLabel();
        playerFourPanel = new javax.swing.JPanel();
        playerFourName = new javax.swing.JLabel();
        playerFourPlace = new javax.swing.JLabel();
        playerThreePanel = new javax.swing.JPanel();
        playerThreeName = new javax.swing.JLabel();
        playerThreePlace = new javax.swing.JLabel();
        playerTwoPanel = new javax.swing.JPanel();
        playerTwoName = new javax.swing.JLabel();
        playerTwoPlace = new javax.swing.JLabel();
        menuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        finalResults.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        finalResults.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        finalResults.setText("Final Results");

        playerOnePanel.setBackground(new java.awt.Color(0, 204, 255));
        playerOnePanel.setBorder(new javax.swing.border.MatteBorder(null));

        playerOneName.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        playerOneName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        playerOnePlace.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        playerOnePlace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout playerOnePanelLayout = new javax.swing.GroupLayout(playerOnePanel);
        playerOnePanel.setLayout(playerOnePanelLayout);
        playerOnePanelLayout.setHorizontalGroup(
            playerOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerOnePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerOneName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerOnePanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(playerOnePlace, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        playerOnePanelLayout.setVerticalGroup(
            playerOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerOnePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerOneName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOnePlace, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        playerFourPanel.setBackground(new java.awt.Color(255, 255, 51));
        playerFourPanel.setBorder(new javax.swing.border.MatteBorder(null));

        playerFourName.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        playerFourName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        playerFourPlace.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        playerFourPlace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout playerFourPanelLayout = new javax.swing.GroupLayout(playerFourPanel);
        playerFourPanel.setLayout(playerFourPanelLayout);
        playerFourPanelLayout.setHorizontalGroup(
            playerFourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerFourPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerFourName, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(playerFourPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(playerFourPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        playerFourPanelLayout.setVerticalGroup(
            playerFourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerFourPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerFourName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerFourPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        playerThreePanel.setBackground(new java.awt.Color(102, 255, 102));
        playerThreePanel.setBorder(new javax.swing.border.MatteBorder(null));

        playerThreeName.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        playerThreeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        playerThreePlace.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        playerThreePlace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout playerThreePanelLayout = new javax.swing.GroupLayout(playerThreePanel);
        playerThreePanel.setLayout(playerThreePanelLayout);
        playerThreePanelLayout.setHorizontalGroup(
            playerThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerThreePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerThreeName, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(playerThreePanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(playerThreePlace, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        playerThreePanelLayout.setVerticalGroup(
            playerThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerThreePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerThreeName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerThreePlace, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        playerTwoPanel.setBackground(new java.awt.Color(255, 51, 51));
        playerTwoPanel.setBorder(new javax.swing.border.MatteBorder(null));

        playerTwoName.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        playerTwoName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        playerTwoPlace.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        playerTwoPlace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout playerTwoPanelLayout = new javax.swing.GroupLayout(playerTwoPanel);
        playerTwoPanel.setLayout(playerTwoPanelLayout);
        playerTwoPanelLayout.setHorizontalGroup(
            playerTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerTwoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerTwoName, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(playerTwoPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(playerTwoPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        playerTwoPanelLayout.setVerticalGroup(
            playerTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerTwoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerTwoName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTwoPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        menuBtn.setText("Back to Menu");
        menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuBtnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(finalResults, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(playerTwoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerOnePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerThreePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerFourPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(finalResults, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerOnePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerTwoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerThreePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerFourPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnMousePressed
        // TODO add your handling code here:
        MainMenu newMenu = new MainMenu();
        newMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBtnMousePressed
/*
NAME
        setResults

SYNOPSIS
        setResults()
    
            No parameters.

DESCRIPTION
        Sets the frame to the results of the game.

RETURNS
        void

AUTHOR
        William Ryan
*/
    private void setResults()
    {
        //holds the players
        ArrayList<Player> players = m_finishedGame.getFinishedPlayers();
        
        //set the frame based on the players
        switch(players.size())
        {
            //2 players 
            case 2:
                playerOneName.setText(m_finishedGame.getFinishedPlayer(1).getPlayerName());
                playerOnePlace.setText("Place: " + (m_finishedGame.getFinishedPlayer(1).getPlayerPlacement()));
                playerTwoName.setText(m_finishedGame.getFinishedPlayer(2).getPlayerName());
                playerTwoPlace.setText("Place: " + (m_finishedGame.getFinishedPlayer(2).getPlayerPlacement()));
                break;
            
            //3 players
            case 3:
                playerOneName.setText(m_finishedGame.getFinishedPlayer(1).getPlayerName());
                playerOnePlace.setText("Place: " + (m_finishedGame.getFinishedPlayer(1).getPlayerPlacement()));
                playerTwoName.setText(m_finishedGame.getFinishedPlayer(2).getPlayerName());
                playerTwoPlace.setText("Place: " + (m_finishedGame.getFinishedPlayer(2).getPlayerPlacement()));
                playerThreeName.setText(m_finishedGame.getFinishedPlayer(3).getPlayerName());
                playerThreePlace.setText("Place: " + (m_finishedGame.getFinishedPlayer(3).getPlayerPlacement()));
                playerThreePanel.setVisible(true);
                break;
            
            //4 players
            case 4:
                playerOneName.setText(m_finishedGame.getFinishedPlayer(1).getPlayerName());
                playerOnePlace.setText("Place: " + (m_finishedGame.getFinishedPlayer(1).getPlayerPlacement()));
                playerTwoName.setText(m_finishedGame.getFinishedPlayer(2).getPlayerName());
                playerTwoPlace.setText("Place: " + (m_finishedGame.getFinishedPlayer(2).getPlayerPlacement()));
                playerThreeName.setText(m_finishedGame.getFinishedPlayer(3).getPlayerName());
                playerThreePlace.setText("Place: " + (m_finishedGame.getFinishedPlayer(3).getPlayerPlacement()));
                playerFourName.setText(m_finishedGame.getFinishedPlayer(4).getPlayerName());
                playerFourPlace.setText("Place: " + (m_finishedGame.getFinishedPlayer(4).getPlayerPlacement()));
                playerThreePanel.setVisible(true);
                playerFourPanel.setVisible(true);
                break;
        }
    }

    //Holds the finished game
    private Game m_finishedGame;
    
    //The following variables were generated by the form editor
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finalResults;
    private javax.swing.JButton menuBtn;
    private javax.swing.JLabel playerFourName;
    private javax.swing.JPanel playerFourPanel;
    private javax.swing.JLabel playerFourPlace;
    private javax.swing.JLabel playerOneName;
    private javax.swing.JPanel playerOnePanel;
    private javax.swing.JLabel playerOnePlace;
    private javax.swing.JLabel playerThreeName;
    private javax.swing.JPanel playerThreePanel;
    private javax.swing.JLabel playerThreePlace;
    private javax.swing.JLabel playerTwoName;
    private javax.swing.JPanel playerTwoPanel;
    private javax.swing.JLabel playerTwoPlace;
    // End of variables declaration//GEN-END:variables
}
